#!/usr/bin/env codecv

"$schema" = "https://raw.githubusercontent.com/hexagonkt/codecv/master/cv.schema.json"

"Job Status" = "not moving"
"Last Update" = 2022-12-27

Locale = "en_US"
Templates = [ "file:cv.html" ]

Bio = """\
  Richard hails from Tulsa. He has earned degrees from the University of Oklahoma and Stanford. \
  (Go Sooners and Cardinals!) Before starting Pied Piper, he worked for Hooli as a part-time \
  software developer. \
  \
  His work focuses on applied information theory, mostly optimizing lossless compression schema of \
  both the length-limited and adaptive variants."""

Goals = [
  "Change the Internet",
  "Make the world a better place",
]

"Top Skills" = [
  "Systems Design",
  "Data structures and Algorithms",
  "Low level Programming",
]

"Other Facts" = [
  "Interested in quantum computing and chaos theory",
  "Wildlife, specially ferrets and unicorns"
]

Links = [
  { Address = "https://github.com/hexagonkt/hexagon" },
  { Address = "https://twitter.com/hexagon_kt" },
  { Address = "https://dev.to/hexagonkt" },
]

[Variables]
gaFont = "family=Roboto+Slab:wght@400;500;700"
colorPrimary = "#087cfa"
gridMaxWidth = "100rem"
gridGutter = "1.5rem"
fontSize = "1.4rem"
fontFamilySans = "Roboto Slab"

[Personal]
"Given Name" = "Richard"
"Family Name" = "Hendricks"
"Native Language" = "en"
"Birth Country" = "US"
Pronoun = "masculine"
Gender = "man"
Birth = "1988-08-16"
Alias = "Bitchard"
Photo = "https://static.wikia.nocookie.net/silicon-valley/images/3/33/Richard_Hendricks.jpg"
Avatar = "https://static.wikia.nocookie.net/silicon-valley/images/3/33/Richard_Hendricks.jpg"
Nationalities = [ "US" ]
Disabilities = [ { Type = "visual", Level = 0.1, Summary = "Can't set font size less than 16." } ]
Ids = [ { Country = "US", Document = "Passport", Id = "A012BC34" } ]
"Driving Licenses" = [ { Country = "US", License = "Class B" } ]

[Residence]
Country = "US"
Region = "California"
City = "San Francisco"
Postcode = "CA 94115"
Address = "2712 Broadway St"

[[Contact]]
Title = "Mobile"
Address = "tel:+1-654-12-34-56"

[[Contact]]
Title = "Landline"
Address = "tel:91-259-11-29"

[[Contact]]
Title = "Email"
Address = "richard@piedpiper.com"

["Target Job"]
"Operating Systems" = [ "linux", "macos" ]
"Desired Skills" = [ "C", "Java" ]
"Excluded Skills" = [ "Node JS" ]
Roles = [ "Developer", "CEO" ]
Features = [ "Courses platform" ]
Remote = { Days = "4d", Period = "7d" }

  [["Target Job".Locations]]
  Country = "US"
  Region = "California"
  City = "San Francisco"
  Postcode = "CA 94115"
  Address = "2712 Broadway St"

  ["Target Job".Salary]
  Money.Amount = 120000.0
  Money.Currency = "USD"
  Period = "1y"
  Gross = true

[[Languages]]
Language = "fr"
Listening = "a1"
Reading = "a2"
Spoken = "b1"
Written = "b2"

[["Personal Projects"]]
Title = "Pied Piper"
Website = "https://example.com"
From = "2010-01"
To = "2011-05"
Summary = "The Google of music."
Roles = [ "Creator", "Developer" ]
Skills = [ "C++" ]

[[Volunteering]]
Position = "Teacher"
Company.Name = "CoderDojo"
Company.Website = "https://coderdojo.com"

  [[Volunteering.Projects]]
  Title = "Kids Coding Teaching"
  From = "2012-01"
  To = "2013-01"
  Highlights = [ "Awarded 'Teacher of the Month'" ]

[[Experience]]
Company.Name = "Pied Piper"
Company.Website = "https://example.net"
Company.Type = "Startup"
Company.Industry = "Software"
Location.Country = "US"
Location.City = "San Francisco"
Position = "Founder"
From = "2013-12"
To = "2014-12"
Summary = "Evolving Internet... And making the world a better place."
"Quit Reason" = "Rats"

  [[Experience.Projects]]
  Title = "Middle-out"
  Website = "https://example.com"
  From = "2010-01"
  To = "2011-05"
  Persons = 6
  Type = "Library"
  Summary = "Groundbreaking compression algorithm."
  Client.Name = "Pied Piper"
  Client.Website = "https://example.net"
  Client.Type = "Startup"
  Client.Industry = "Software"
  Production = true
  Highlights = [ "Techcrunch Disrupt Winner" ]
  Roles = [ "Developer", "CEO" ]
  Skills = [ "C" ]

[[Education]]
Title = "Bachelor's Degree in Computer Science"
Type = "Bachelor"
Institution.Name = "University of Oklahoma"
Institution.Website = "https://example.net"
From = "1996-09"
To = "2000-06"
Website = "https://example.org"
Area = "Computer Science"
Location.Country = "US"
Location.Region = "Oklahoma"
Location.City = "Norman"
Summary = "Computer science and internship at Hooli."
Score = "A+"
Subjects = [
  "DB1101 - Basic SQL",
  "CS2011 - Java Introduction"
]

[[Courses]]
Title = "Cloud Deployment and Monitoring"
Institution.Name = "Bachman Consulting"
Institution.Website = "https://example.org"
From = "2014-06-01"
To = "2014-06-05"
Website = "https://example.org"
Area = "DevOps"
Location.Country = "US"
Location.City = "San Francisco"
Summary = "Infrastructure as code, continuous monitoring and alerting, container."
Company = "Pied Piper"
Hours = 35
Score = "A"
Subjects = [ "Kubernetes", "Docker", "Grafana" ]

[[Achievements]]
Type = "award"
Title = "Digital Compression Pioneer Award"
Date = "2014-11-01"
Website = "https://example.com"
Summary = "There is no spoon."
Issuer.Name = "Techcrunch"

[[Achievements]]
Type = "presentation"
Title = "Building an algorithm for copy right infringement detection"
Date = "2012-09-05"

[[Achievements]]
Type = "publication"
Title = "Video compression for 3d media"
Date = "2014-10-01"
Website = "http://example.net"
Summary = "Innovative middle-out compression algorithm that changes the way we store data."
Issuer.Name = "Hooli"

[[References]]
"Full Name" = "Erlich Bachman"
"Social Profiles" = [ "https://github.com/hexagonkt/hexagon" ]
Type = "manager"
Projects = [ "middle-out" ]
Summary = """\
  It is my pleasure to recommend Richard, his performance working as a consultant for Bachman \
  Consulting proved that he will be a valuable addition to any company."""

  [[References.Contact]]
  Title = "Mobile"
  Address = "tel:+1-678-20-41-05"

  [[References.Contact]]
  Title = "Landline"
  Address = "tel:91-106-28-01"

  [[References.Contact]]
  Title = "Email"
  Address = "erlich@aviato.com"

[["Technical Skills"]]
Title = "Compression"
Skills = [ "Mpeg", "MP4", "GIF" ]

[["Technical Skills"]]
Title = "Systems Programming"

[["Common Skills"]]
Title = "Productivity"
Skills = [ "Vim", "Typewriting" ]
